# Generated by Django 5.0.7 on 2024-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_attendance_employee_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
