# Generated by Django 5.0.7 on 2024-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='comment',
            new_name='description',
        ),
    ]
